// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: server.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RusprofileGrpcWrapClient is the client API for RusprofileGrpcWrap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RusprofileGrpcWrapClient interface {
	FirmInfoGet(ctx context.Context, in *InnRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type rusprofileGrpcWrapClient struct {
	cc grpc.ClientConnInterface
}

func NewRusprofileGrpcWrapClient(cc grpc.ClientConnInterface) RusprofileGrpcWrapClient {
	return &rusprofileGrpcWrapClient{cc}
}

func (c *rusprofileGrpcWrapClient) FirmInfoGet(ctx context.Context, in *InnRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/rusprofileGrpcWrap.RusprofileGrpcWrap/FirmInfoGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RusprofileGrpcWrapServer is the server API for RusprofileGrpcWrap service.
// All implementations must embed UnimplementedRusprofileGrpcWrapServer
// for forward compatibility
type RusprofileGrpcWrapServer interface {
	FirmInfoGet(context.Context, *InnRequest) (*InfoResponse, error)
	mustEmbedUnimplementedRusprofileGrpcWrapServer()
}

// UnimplementedRusprofileGrpcWrapServer must be embedded to have forward compatible implementations.
type UnimplementedRusprofileGrpcWrapServer struct {
}

func (UnimplementedRusprofileGrpcWrapServer) FirmInfoGet(context.Context, *InnRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FirmInfoGet not implemented")
}
func (UnimplementedRusprofileGrpcWrapServer) mustEmbedUnimplementedRusprofileGrpcWrapServer() {}

// UnsafeRusprofileGrpcWrapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RusprofileGrpcWrapServer will
// result in compilation errors.
type UnsafeRusprofileGrpcWrapServer interface {
	mustEmbedUnimplementedRusprofileGrpcWrapServer()
}

func RegisterRusprofileGrpcWrapServer(s grpc.ServiceRegistrar, srv RusprofileGrpcWrapServer) {
	s.RegisterService(&RusprofileGrpcWrap_ServiceDesc, srv)
}

func _RusprofileGrpcWrap_FirmInfoGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RusprofileGrpcWrapServer).FirmInfoGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusprofileGrpcWrap.RusprofileGrpcWrap/FirmInfoGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RusprofileGrpcWrapServer).FirmInfoGet(ctx, req.(*InnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RusprofileGrpcWrap_ServiceDesc is the grpc.ServiceDesc for RusprofileGrpcWrap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RusprofileGrpcWrap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rusprofileGrpcWrap.RusprofileGrpcWrap",
	HandlerType: (*RusprofileGrpcWrapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FirmInfoGet",
			Handler:    _RusprofileGrpcWrap_FirmInfoGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
